<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>WarpSystem</artifactId>
        <groupId>de.codingair</groupId>
        <version>5.1.14_Hotfix-9</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>WarpSystem-Bundle-Free</artifactId>

    <properties>
        <maven.compiler.target>1.8</maven.compiler.target>
        <maven.compiler.source>1.8</maven.compiler.source>
    </properties>

    <build>
        <finalName>WarpSystem_v${project.version}-free</finalName>

        <resources>
            <resource>
                <directory>${basedir}/src/main/resources</directory>
                <targetPath>.</targetPath>
                <filtering>true</filtering>
                <includes>
                    <include>*</include>
                    <include>*/**</include>
                </includes>
            </resource>
        </resources>

        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <version>3.2.3</version>

                <configuration>
                    <dependencyReducedPomLocation>${project.build.directory}/dependency-reduced-pom.xml</dependencyReducedPomLocation>
                    <relocations>
                        <relocation>
                            <pattern>de.codingair.codingapi</pattern>
                            <shadedPattern>de.codingair.warpsystem.lib.codingapi</shadedPattern>
                        </relocation>
                        <relocation>
                            <pattern>de.codingair.packetmanagement</pattern>
                            <shadedPattern>de.codingair.warpsystem.lib.packetmanagement</shadedPattern>
                        </relocation>
                        <relocation>
                            <pattern>io.papermc.lib</pattern>
                            <shadedPattern>de.codingair.warpsystem.lib.papermc</shadedPattern>
                        </relocation>
                        <relocation>
                            <pattern>org.bstats</pattern>
                            <shadedPattern>de.codingair.warpsystem.lib.bstats</shadedPattern>
                        </relocation>
                        <relocation>
                            <pattern>org.jetbrains.annotations</pattern>
                            <shadedPattern>de.codingair.warpsystem.lib.annotations</shadedPattern>
                        </relocation>
                        <relocation>
                            <pattern>org.intellij.lang.annotations</pattern>
                            <shadedPattern>de.codingair.warpsystem.lib.annotations</shadedPattern>
                        </relocation>
                    </relocations>
                </configuration>

                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jar-plugin</artifactId>
                <configuration>
                    <archive>
                        <manifestEntries>
                            <paperweight-mappings-namespace>mojang</paperweight-mappings-namespace>
                        </manifestEntries>
                    </archive>
                </configuration>
            </plugin>
        </plugins>
    </build>

    <dependencies>
        <dependency>
            <groupId>com.github.CodingAir</groupId>
            <artifactId>CodingAPI</artifactId>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>com.github.CodingAir</groupId>
            <artifactId>PacketManagement</artifactId>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>io.papermc</groupId>
            <artifactId>paperlib</artifactId>
            <scope>compile</scope>
        </dependency>

        <dependency>
            <groupId>${project.groupId}</groupId>
            <artifactId>WarpSystem-Core</artifactId>
            <version>${project.version}</version>
            <scope>compile</scope>
        </dependency>

        <dependency>
            <groupId>${project.groupId}</groupId>
            <artifactId>WarpSystem-Spigot</artifactId>
            <version>${project.version}</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>${project.groupId}</groupId>
            <artifactId>WarpSystem-Spigot-Free</artifactId>
            <version>${project.version}</version>
            <scope>compile</scope>
        </dependency>

        <dependency>
            <groupId>${project.groupId}</groupId>
            <artifactId>WarpSystem-Proxy-Core</artifactId>
            <version>${project.version}</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>${project.groupId}</groupId>
            <artifactId>WarpSystem-Proxy-BungeeCord</artifactId>
            <version>${project.version}</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>${project.groupId}</groupId>
            <artifactId>WarpSystem-Proxy-Velocity</artifactId>
            <version>${project.version}</version>
            <scope>compile</scope>
        </dependency>

        <dependency>
            <groupId>com.github.CodingAir</groupId>
            <artifactId>WarpSystem-API</artifactId>
            <scope>compile</scope>
        </dependency>
    </dependencies>
</project>