<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>WarpSystem-Proxy</artifactId>
        <groupId>de.codingair</groupId>
        <version>5.1.14_Hotfix-10</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>WarpSystem-Proxy-Velocity</artifactId>

    <properties>
        <maven.compiler.target>1.8</maven.compiler.target>
        <maven.compiler.source>1.8</maven.compiler.source>
    </properties>

    <build>
        <resources>
            <resource>
                <directory>${basedir}/src/main/resources</directory>
                <targetPath>.</targetPath>
                <filtering>true</filtering>
                <includes>
                    <include>*</include>
                    <include>*/**</include>
                </includes>
            </resource>
        </resources>
    </build>

    <repositories>
        <repository>
            <id>papermc</id>
            <url>https://repo.papermc.io/repository/maven-public/</url>
        </repository>
    </repositories>

    <dependencies>
        <dependency>
            <groupId>${project.groupId}</groupId>
            <artifactId>WarpSystem-Core</artifactId>
            <version>${project.version}</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>${project.groupId}</groupId>
            <artifactId>WarpSystem-Proxy-Core</artifactId>
            <version>${project.version}</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>com.github.CodingAir</groupId>
            <artifactId>CodingAPI</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>com.github.CodingAir</groupId>
            <artifactId>PacketManagement</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>com.velocitypowered</groupId>
            <artifactId>velocity-api</artifactId>
            <version>3.1.1</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>com.github.ProxioDev.ValioBungee</groupId>
            <artifactId>RedisBungee-Velocity</artifactId>
            <version>0.12.6</version>
            <scope>provided</scope>
        </dependency>
    </dependencies>

</project>